# Logger configuration file for ratbag
# See https://docs.python.org/3/library/logging.config.html for details on
# this format
#
# Save this file as
# - $XDG_CONFIG_HOME/ratbagd/config-logger.yml
# - $PWD/config-logger.yml
#
# To apply the config to ratbagcli and other tools
version: 1
formatters:
  simple:
    format: '%(levelname).1s|%(name)s: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stderr
loggers:
  ratbag:
    level: DEBUG
    handlers: [console]
    propagate: no
  ratbag.driver:
    level: DEBUG
    handlers: [console]
    propagate: no
  ratbag.drivers.*:
    level: DEBUG
    handlers: [console]
    propagate: no
  ratbag.parser:
    level: DEBUG
    handlers: [console]
    propagate: no
  ratbagd:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]
